language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"

install:
 - pip install --upgrade setuptools pip
 - pip install -r test-requirements.txt
 - pip install -e .
script: python -m unittest2 discover

matrix:
  allow_failures:
    - python: "3.4"
    - python: "3.5"
